# Generated by Django 2.2 on 2019-04-09 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=2000)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_username', models.CharField(max_length=200)),
                ('twitter_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trusted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expert', to='interest.Person')),
                ('twittertag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interest.HashTag')),
            ],
        ),
        migrations.AddField(
            model_name='hashtag',
            name='person',
            field=models.ManyToManyField(through='interest.Trusted', to='interest.Person'),
        ),
    ]
