# Generated by Django 2.2 on 2019-04-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0003_auto_20190409_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='tags',
        ),
    ]
