# Generated by Django 2.2 on 2019-04-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetag',
            name='namespace_slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='machinetag',
            name='predicate_slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='machinetag',
            name='value_slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='machinetag',
            unique_together={('namespace', 'predicate', 'value')},
        ),
        migrations.DeleteModel(
            name='MachineTaggedItem',
        ),
    ]
