# Generated by Django 2.2 on 2019-04-10 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('machinetag', '0002_auto_20190410_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetag',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='machinetag',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
