# Generated by Django 2.2 on 2019-04-10 03:47

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('machinetag', '0003_auto_20190410_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinetag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='machinetag',
            name='object_id',
        ),
        migrations.AddField(
            model_name='machinetag',
            name='tagged',
            field=gm2m.fields.GM2MField(through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
    ]
