# Generated by Django 2.2 on 2019-05-15 04:03

from django.db import migrations, models
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('machinetag', '0004_auto_20190410_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinetag',
            name='label',
            field=models.CharField(blank=True, default='', editable=False, max_length=600),
        ),
        migrations.AlterField(
            model_name='machinetag',
            name='tagged',
            field=gm2m.fields.GM2MField('interest.Link', 'rss.Feed', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
    ]
